#!/usr/bin/env python3

import textwrap
import colorama
import sys

from xmlrpc.client import ServerProxy
from rst2ansi import rst2ansi

def ask():
    colorama.init()

    client = ServerProxy('http://localhost:4224/', allow_none=True)
    try:
        client.ping()
    except ConnectionRefusedError:
        print('Sorry, the git gud server seems to be down.')
        exit(1)

    print('How can I help you git gud? (enter \'quit\' or press Ctrl-D to exit)')

    while True:
        import readline
        try:
            query = input('>> ')
        except KeyboardInterrupt:
            print()
            continue
        except EOFError:
            print('quit')
            break

        if query in {'quit', 'q', 'leave', 'exit', 'bye'}:
            break

        response = client.query(query)
        if response:
            out = rst2ansi(response)
            out = textwrap.indent(out, colorama.Style.DIM + '<< ' + colorama.Style.NORMAL, lambda line: True)

            print()
            print(out)
            print()

if __name__ == '__main__':
    ask()
